### PR TITLE
Terminal vim

### LINKED ISSUE #4: Unable to open files on command line
Thanks for providing the appimage of Vim. This is very helpful to work with a recent Vim version on my very old Ubuntu at work.
I'm having some trouble starting Vim on command line with a file as argument. For example `$PWD` is `$HOME` and I issue `~/bin/GVim-v8.1.0139-gita8a60d0c6-glibc2.15.glibc2.15-x86_64.AppImage .bashrc` Vim will open a file in `/tmp/.mount_qMpnvg/usr/.bashrc` instead of `$HOME/.bashrc`. I tried to add `-c "cd $PWD"` which has no effect as it is executed after reading the file. Adding `--cmd "cd $PWD"` does not work because in this case the runtimepath variable contains wrong directories (not absolute paths) and the distributed configuration is not found.

Any ideas how to get this running?

### PR DESCRIPTION
**Pull request by rakus**
# Rework build, support terminal Vim

- allow to run GVim or Vim depending on the name of AppImage file (or the symlink to it)
- support building and release via Travis cron job
- allow `cd` from inside Vim

### Using AppImageKit V11
The script `scripts/appimage.sh` downloads a file name [`functions.sh`](https://github.com/probonopd/AppImages/raw/master/functions.sh). This script uses v6 of the AppImageKit.

Copied some lines from `functions.sh` to `appimage.sh` and changed the URLs to use AppImageKit v11 (newest release). Important new feature: `ARGV0`, see below.

### Startup
The `gvim.desktop` file is changed to call a script named `vim.startup.sh`. This script ...
- Sets the environment variables `VIM` and `VIMRUNTIME` (if not already set). With this Vim can `cd` to other directories and still find its runtime files.
- Unsets Python related variables set by AppImageKit. As Python is not packed into the image, we rely on host provided Python.
- Evaluates the env var `ARGV0` set by AppImageKit. This variable contains the name the executable was started with. If the name starts with `vim`, terminal Vim is started, else GVim is started. Now you can create a symlink `vim.appimage -> GVim*.AppImage` to get a terminal Vim.
- Returns to the directory the AppImage was started from. AppImageKit sets the env var `OWD` for this. This fixes #4.

### Building

1. Travis always checks out the "master" branch of the submodule vim and pulls the newest changes.
2. Install needed dependencies copied from `.travis.yml` of Vim.
3. Script `make_vim.sh` is used to build Vim.
4. The Version is determined from the last tag from Vim and the vim-appimage repo is tagged accordingly after a successful build.
5. A minimal body text for the Github release.
6. Removed git commit from version/file name. Looked ugly IMHO.
7. API-Token is now held in the Travis configuration (not as encrypted key in `.travis.yml`)

With this setup it is possible to build the AppImage with Travis cron jobs. So it is build daily and will
automatically pick up the current Vim patch level, create a tag and a GitHub release.

E.g. [Release v8.1.1211](https://github.com/rakus/vim-appimage/releases/tag/v8.1.1211) was created by a Travis [cron job](https://travis-ci.org/rakus/vim-appimage/builds/525329659).

Building via `make_vim.sh` is useful for local builds, also `scripts/appimage.sh` uses a different build directory when not on Travis.

The last point (API-Token) could be reverted. This way it was easier for me to test deployment to GitHub releases.

## Testing

It is possible to copy the `GVim*.AppImage` file to `vim/src/vim` and then start `make test`.

This is currently not part of the Travis build, but could be added if wanted.

## Before Merging this PR
Cleanup `.travis.yml`, so deployment to GitHub is only done on master branch (just comment section `on:` in `deploy:`).

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. that are many changes. What's the thing about $API_TOKEN? That is not defined anywhere?
I don't understand that part:

> Cleanup .travis.yml, so deployment to GitHub is only done on master branch (just comment section on: in deploy:).

That is already commented and your last commit does already un-comment it? So what should be done before merging this?

**Comment by chrisbra** [comment]
I didn't even notice, there was an open issue #4 here. Sorry for that.

**Comment by rakus** [comment]
Regarding API_TOKEN: Authentication is needed for the deployment to GitHub. And there are two ways to do that. Either with a secure (aka encrypted) "api-key" in `.travis.yml`. The other way is to add the key to the project configuration on travis as a protected environment variable. 

If this merge request is approved for merging by you, I would add a last commit to:
1. Uses the secure api-key as it was used before
2. To only deploy if the master branch is built.

In the current state I'm able to test deployment in my forked repo on my development branch.

**Comment by chrisbra** [comment]
ah okay, please go ahead :)

**Comment by rakus** [comment]
I realized a "problem" with the PR. During travis build it updates the Vim submodule. This changes have to be committed and must be pushed back to Github. I'm investigating.

I could continue in two directions:

1. Continue with the PR as is and add push back to GitHub
2. Split into two PRs. One for new AppImage build (new AppImageKit & allow terminal Vim) and another for updating Vim during Travis build, commiting and push to GitHub.

**Comment by chrisbra** [comment]
ah okay. If possible, I would suggest to split up the PR.

**Comment by rakus** [comment]
Christian, I feared you would choose the second option :-).
I would have done the same.

BTW: This a [commit created by Travis](https://github.com/rakus/vim-appimage/commit/9bd715a6530997481b5bc019b813eb96f1006015)

**Comment by rakus** [comment]
Closing this pull request, as it will be splitted into two separate PRs.

**Pull request closed without merging**
